name: ml-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - nltk>=3.7
  - wordcloud>=1.9.0
  - plotly>=5.0.0
  - pip
  - pip:
    - jupyter-contrib-nbextensions
    - fastapi>=0.95.0
    - uvicorn>=0.20.0
    - joblib>=1.2.0
    - textblob>=0.17.0 